In [1]:
import usecsv
import numpy as np

In [3]:
# quest.csv 파일을 열어 숫자 원소를 실수형으로 변환 => quest 객체에 저장
quest = np.array(usecsv.switch(usecsv.opencsv('quest.csv')))

print(quest)

[[1. 2. 1. 2. 2.]
 [1. 3. 2. 3. 2.]
 [1. 4. 3. 3. 3.]
 [2. 5. 4. 4. 4.]
 [2. 5. 6. 2. 5.]
 [3. 6. 4. 2. 5.]
 [3. 5. 4. 1. 6.]
 [3. 5. 5. 1. 3.]]


In [4]:
# 배열에 연산자를 대입하면 모든 데이터에 연산자를 적용한다.
print(quest > 5)

[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False  True False False]
 [False  True False False False]
 [False False False False  True]
 [False False False False False]]


In [5]:
# 5보다 큰 배열의 요소를 5로 바꾼다.
quest[quest > 5] = 5
print(quest)

[[1. 2. 1. 2. 2.]
 [1. 3. 2. 3. 2.]
 [1. 4. 3. 3. 3.]
 [2. 5. 4. 4. 4.]
 [2. 5. 5. 2. 5.]
 [3. 5. 4. 2. 5.]
 [3. 5. 4. 1. 5.]
 [3. 5. 5. 1. 3.]]


In [6]:
# 결과 파일을 csv 파일로 다시 내보낸다.
usecsv.writecsv('resultquest.csv', list(quest))