In [1]:
from sklearn import datasets
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
import numpy as np

In [2]:
# 데이터셋을 읽고 훈련 집합과 테스트 집합으로 분할
digit = datasets.load_digits()
x_train, x_test, y_train, y_test = train_test_split(digit.data, digit.target, train_size=0.6)

In [4]:
# fit 함수로 Perceptron 학습
p = Perceptron(max_iter=100, eta0=0.001, verbose=0)
p.fit(x_train, y_train)

Perceptron(eta0=0.001, max_iter=100)

In [5]:
res = p.predict(x_test) # 테스트 집합으로 예측

In [6]:
# 혼동 행렬
conf = np.zeros((10, 10))
for i in range(len(res)):
    conf[res[i]][y_test[i]]+=1
print(conf)

[[68.  0.  0.  0.  0.  1.  0.  0.  0.  1.]
 [ 0. 70.  0.  1.  1.  1.  3.  1.  8.  1.]
 [ 0.  0. 72.  4.  0.  0.  0.  0.  4.  0.]
 [ 0.  0.  0. 57.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0. 72.  0.  0.  2.  0.  3.]
 [ 0.  0.  0.  2.  0. 71.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1. 64.  0.  0.  0.]
 [ 0.  1.  1.  0.  1.  0.  0. 65.  3.  1.]
 [ 0.  0.  0.  1.  0.  0.  0.  0. 53.  1.]
 [ 0.  0.  0.  5.  4.  2.  0.  1.  1. 70.]]


In [7]:
# 정확률 계산
no_correct = 0
for i in range(10):
    no_correct += conf[i][i]
accuracy = no_correct / len(res)
print("테스트 집합에 대한 정확률은 ", accuracy*100, "%입니다.")

테스트 집합에 대한 정확률은  92.07232267037551 %입니다.
